version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_practicas
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: gestion_practicas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # Conexión al contenedor 'db'
      DATABASE_URL: postgresql://user_practicas:password123@db:5432/gestion_practicas
    depends_on:
      - db

volumes:
  postgres_data: